matchClipboard: https?://((www\.)?bilibili\.com/video/[a-zA-Z0-9]+|b23\.tv/[a-zA-Z0-9]+|(www\.)?youtube\.com/(shorts/|watch\?v=)[a-zA-Z0-9-]+|youtu\.be/[a-zA-Z0-9]+)
packages: lux
packages.pip: yt-dlp
singleInstance: false
